# Generated by Django 5.1.6 on 2025-03-14 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('card_brand', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=50)),
                ('front_image', models.ImageField(upload_to='cards/front/')),
                ('back_image', models.ImageField(upload_to='cards/back/')),
                ('for_sale', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
